# This is a workflow to test your PowerShell module with TestingHelper
# https://github.com/rulasg/DemoPsModule/blob/main/.github/workflows/test_with_TestingHelper.yml

name: Test TestingHelper Setup Action

# Controls when the workflow will run
on:

  # Push and push-pr events trigger the workflow
  push:
      branches: [ main ]
  pull_request:

  # Allow to be called from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # To run test we only need to read the repository
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Run test with TestingHelper using local branch version
      - name: Run local action
        uses: ./

      - name: Assert the test run
        shell: pwsh
        run: |
            ./test.ps1

